### ISSUE TITLE
anime lame

### ISSUE THREAD

**Issue by groozchique** [TwistedKernel/Twisted-845#2]
![6ff3422021c92371d9a89043cc5ada7f](https://user-images.githubusercontent.com/28346376/72228100-b2e5a000-35b4-11ea-8ced-5aa9649ba3f7.JPG)

**Comment by TwistedPrime** [comment]
Koff
![sticker (24)](https://user-images.githubusercontent.com/36546624/72262567-1bfa0180-360f-11ea-81df-8ae68f6183e7.png)

⠀⠀⠀⠀⠀⠀⠀⢀⠀⠂⠂⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠠⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠄⠈⠐⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢂⠀⠀⠀⠀
⠀⠀⠀⠀⡐⠀⠀⠀⠀⠀⠀⠀⢡⠀⠀⠀⠀⠀⠀⠀⠀⠀⠊⠀⠀⢸⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⡠⠀⠀⠀⠑⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠉⠀⠀⠀⠀⠀⢣⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀⠀⢣⠀⠀⠀
⠀⠀⠀⢸⠀⠀⠀⡜⠀⡆⠀⠀⠀⢀⣲⠀⠀⠀⠀⠀⠀⠴⠀⠀⡇⠀⠀⡀⠀⠀
⠀⠀⠀⡜⠀⠀⠁⠀⠀⠘⠀⠀⠀⠀⠀⢘⣄⠀⠀⠀⡜⣀⠀⢠⠉⠀⠀⢠⠀⠀
⠀⠀⠀⣄⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⢠⠀⠈⠛⠛⠒⡀⠀⡇⠀⡄⠀⠈⠀⠀
⠀⠀⠀⢒⠀⠀⡱⠀⠀⠀⠎⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠀⠇⠀⠈⠀⠀⠀⠀
⠀⠀⠀⢸⠀⢠⠀⠀⠀⢸⠀⠀⠀⠀⢀⠀⠙⠁⠀⠁⣉⠊⠀⡆⠀⠀⠈⠀⡅⠀
⠀⠀⠀⠀⡀⠈⠀⠀⠀⠃⠀⠀⠀⠀⡌⠈⠀⠑⠃⠋⠀⠀⠀⡇⠀⠀⠀⠀⢠⠀
⠀⠀⠀⠀⠘⠀⠈⡀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⡀⠈⠀
⠀⠀⠀⠀⠀⣂⢀⢸⠀⢱⢀⣤⢀⠀⠃⠀⠀⠀⠀⢂⠀⠀⠂⠂⠀⠀⠀⣘⡈⡀
⠀⠀⠀⠀⠀⠀⠠⠹⠓⢸⠀⠀⢀⠓⠀⠀⠀⠀⠀⡞⢀⠀⢀⠀⠀⠀⠐⢹⠂⠀
⠀⠀⠀⠀⠀⠀⠀⠈⠛⠇⠀⠀⠃⠀⠀⠀⠀⠀⠀⠀⠀⠂⠁⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⢰⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⡌⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠊⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⡠⠀⠀⠀⠀⠀⠀⡆⠀⢰⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠊⠠⠂⠉⢤⣀⠀⠀⠀⠀⢠⠀⠐⠣⠠⢤⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠁⠂⠤⠼⠓⠓⠒⠀⠀⠀⠈⠂⠀⠀⠀⠂⠚⠁⠀⠀

**Comment by groozchique** [comment]
Author of the kernel is mean, 1 star on XDA thread for that

**Comment by groozchique** [comment]
WTF NIGGA FIX YOUR GODDAMNED KERNEL

**Comment by TwistedPrime** [comment]
Neger no
